trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Maven_Build_Java_Stage
  jobs:
  - job: Maven_Build_Job
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'MyJavaApp'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        artifactName: 'MyJavaApp'
        downloadPath: '$(Build.ArtifactStagingDirectory)/MyJavaApp'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/MyJavaApp'
        Contents: '**'
        targetFolder: '$(System.DefaultWorkingDirectory)/MyJavaApp'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/MyJavaApp
          # run deploy script or command to deploy the application
