trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'MyJavaApp'
        publishLocation: 'Container'
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        artifactName: 'MyJavaApp'
        downloadPath: '$(Build.ArtifactStagingDirectory)/MyJavaApp'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/MyJavaApp'
        Contents: '**'
        targetFolder: '$(System.DefaultWorkingDirectory)/MyJavaApp'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/MyJavaApp
          # run deploy script or command to deploy the application
