trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  major: 1
  minor: 0
  patch: 0
  incrementNumber: 0

stages:
- stage: Versioning
  jobs:
    - job: semantic_versioning
      steps:
        - script: |
            currentMajor=$(Build.Major)
            currentMinor=$(Build.Minor)
            currentPatch=$(Build.Patch)
            echo "Major version changed from $currentMajor to $newMajor. Resetting minor, patch, and increment-number."
            echo "##vso[task.setvariable variable=major]$newMajor"
            echo "##vso[task.setvariable variable=minor]0"
            echo "##vso[task.setvariable variable=patch]0"
            echo "##vso[task.setvariable variable=incrementNumber]0"
- stage: Maven_Build_Java_Stage
  jobs:
  - job: Maven_Build_Job
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: CopyFiles@2
      inputs:
        Contents: 'target/**'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
    
- stage: Download_Artifact_Stage
  jobs:
  - job: Download_Artifact_job
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        artifactName: 'drop'
        downloadPath: '$(Build.ArtifactStagingDirectory)/drop'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)/drop'
        Contents: '**/*.war'
        targetFolder: '$(System.DefaultWorkingDirectory)/drop'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)/drop
          ls $(System.DefaultWorkingDirectory)/drop
          # run deploy script or command to deploy the application
