resources:
  repositories:
    - repository: shared-templates
      type: github
      endpoint: SreenivasanVr
      name: SreenivasanVr/shared-templates
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - template: maven-java-template.yml
    parameters:
      buildProjectName: My_First_Java_Project
      pipeline_artifact_name: javajar
      