resources:
  repositories:
    - repository: shared_templates
      type: github
      endpoint: SreenivasanVr
      name: SreenivasanVr/shared_templates
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - template: maven_java_template.yml@shared_templates
  - stage:
    jobs:
      - job: 
        steps:
          - script: echo passed
      