resources:
  repositories:
    - repository: any_name_template
      type: github
      endpoint: SreenivasanVr
      name: shared-templates
trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - template: 4.java-build-template-using-stages.yml@shared-templates
    parameters:
      buildProjectName: My_First_Java_Project
      pipeline_artifact_name: javajar
      