trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Script_Stage
    displayName: 'Learning Scripts'    
    jobs:
      - job: Script_Job
        steps:
          - script: echo Hello World
            displayName: 'Run a One line Script'
          - script: |
              echo add other task to build, deploy and test
              echo this is for testing
            displayName: 'This is a Multiline Script'   
  - stage: Build_Maven_Project_Stage
    displayName: 'Building Java Maven Projects'
    jobs:
      - job: Build_Maven_Job
        steps:
          - script: echo Hello World 2
            displayName: 'Run a One line Script'
          - script: |
              echo add other task to build, deploy and test
              echo this is for testing
            displayName: 'This is a Multiline Script'
          - task: Maven@3
            displayName: 'Maven Build'
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
      - deployment: deploy
        environment: DVLP
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deployment task
    
